package pojos;
// Generated 10 ene 2023 11:23:34 by Hibernate Tools 6.1.5.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Inventory generated by hbm2java
 */
public class Inventory implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer inventoryId;
	private Film film;
	private Store store;
	private Timestamp lastUpdate;
	private Set rentals = new HashSet(0);

	public Inventory() {
	}

	public Inventory(Film film, Store store, Timestamp lastUpdate) {
		this.film = film;
		this.store = store;
		this.lastUpdate = lastUpdate;
	}

	public Inventory(Film film, Store store, Timestamp lastUpdate, Set rentals) {
		this.film = film;
		this.store = store;
		this.lastUpdate = lastUpdate;
		this.rentals = rentals;
	}

	public Integer getInventoryId() {
		return this.inventoryId;
	}

	public void setInventoryId(Integer inventoryId) {
		this.inventoryId = inventoryId;
	}

	public Film getFilm() {
		return this.film;
	}

	public void setFilm(Film film) {
		this.film = film;
	}

	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	public Timestamp getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Timestamp lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Set getRentals() {
		return this.rentals;
	}

	public void setRentals(Set rentals) {
		this.rentals = rentals;
	}

}
