package pojos;
// Generated 10 ene 2023 11:23:34 by Hibernate Tools 6.1.5.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Store generated by hbm2java
 */
public class Store implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Byte storeId;
	private byte managerStaffId;
	private short addressId;
	private Timestamp lastUpdate;
	private Set inventories = new HashSet(0);

	public Store() {
	}

	public Store(byte managerStaffId, short addressId, Timestamp lastUpdate) {
		this.managerStaffId = managerStaffId;
		this.addressId = addressId;
		this.lastUpdate = lastUpdate;
	}

	public Store(byte managerStaffId, short addressId, Timestamp lastUpdate, Set inventories) {
		this.managerStaffId = managerStaffId;
		this.addressId = addressId;
		this.lastUpdate = lastUpdate;
		this.inventories = inventories;
	}

	public Byte getStoreId() {
		return this.storeId;
	}

	public void setStoreId(Byte storeId) {
		this.storeId = storeId;
	}

	public byte getManagerStaffId() {
		return this.managerStaffId;
	}

	public void setManagerStaffId(byte managerStaffId) {
		this.managerStaffId = managerStaffId;
	}

	public short getAddressId() {
		return this.addressId;
	}

	public void setAddressId(short addressId) {
		this.addressId = addressId;
	}

	public Timestamp getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Timestamp lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Set getInventories() {
		return this.inventories;
	}

	public void setInventories(Set inventories) {
		this.inventories = inventories;
	}

}
